const menuItems = [
  {
    id: "1",
    name: "Margherita Classic",
    description:
      "San Marzano tomatoes, fresh mozzarella, basil, extra virgin olive oil",
    price: { regular: 100, medium: 180 },
    category: "pizza",
    image: "/images/margherita.jpg",
  },
  {
    id: "4",
    name: "Onion Pizza",
    description:
      "Caramelized onions on a tangy tomato base with gooey mozzarella",
    price: { regular: 150, medium: 220 },
    category: "pizza",
    image: "/images/onion-pizza.jpg",
  },
  {
    id: "5",
    name: "Tomato Pizza",
    description: "Fresh tomato slices with herbs and a blend of cheeses",
    price: { regular: 140, medium: 200 },
    category: "pizza",
    image: "/images/tomato-pizza.jpg",
  },
  {
    id: "6",
    name: "Capsicum Pizza",
    description:
      "Crunchy capsicum strips with spicy seasoning and melted cheese",
    price: { regular: 160, medium: 230 },
    category: "pizza",
    image: "/images/capsicum-pizza.jpg",
  },
  {
    id: "7",
    name: "Mix Pizza",
    description:
      "Colorful combination of onions, tomatoes, capsicum and mushrooms",
    price: { regular: 170, medium: 240 },
    category: "pizza",
    image: "/images/mix-pizza.jpg",
  },
  {
    id: "8",
    name: "Mushroom Pizza",
    description: "Sautéed mushrooms with garlic butter and Parmesan topping",
    price: { regular: 160, medium: 230 },
    category: "pizza",
    image: "/images/mushroom-pizza.jpg",
  },
  {
    id: "9",
    name: "Paneer Pizza",
    description: "Soft cottage cheese cubes with Indian spices and herbs",
    price: { regular: 180, medium: 250 },
    category: "pizza",
    image: "/images/paneer-pizza.jpg",
  },
  {
    id: "10",
    name: "Corn Cheese Pizza",
    description: "Sweet corn kernels with double cheese topping",
    price: { regular: 160, medium: 230 },
    category: "pizza",
    image: "/images/corn-cheese-pizza.jpg",
  },
  {
    id: "11",
    name: "Farm House Pizza",
    description:
      "Hearty mix of onion, paprika, capsicum, corn, tomato, mushroom",
    price: { regular: 190, medium: 260 },
    category: "pizza",
    image: "/images/farmhouse-pizza.jpg",
  },
  {
    id: "12",
    name: "Paneer Delight Pizza",
    description: "Marinated paneer with red paprika and capsicum",
    price: { regular: 200, medium: 270 },
    category: "pizza",
    image: "/images/paneer-delight-pizza.jpg",
  },
  {
    id: "13",
    name: "American Pizza",
    description: "Jalapeños, paprika, and capsicum with Mexican seasoning",
    price: { regular: 180, medium: 250 },
    category: "pizza",
    image: "/images/american-pizza.jpg",
  },
  {
    id: "14",
    name: "Spicy Italian Pizza",
    description: "Fiery combination of jalapeños, onions, and Italian herbs",
    price: { regular: 190, medium: 260 },
    category: "pizza",
    image: "/images/spicy-italian-pizza.jpg",
  },
  {
    id: "15",
    name: "Sandwich Pizza",
    description: "Unique double-decker pizza with grilled vegetable layers",
    price: { regular: 210, medium: 280 },
    category: "pizza",
    image: "/images/sandwich-pizza.jpg",
  },

  // Burger Items
  {
    id: "16",
    name: "Aloo Tikki Burger",
    description: "Crispy potato patty with mint chutney in sesame bun",
    price: 60,
    category: "burger",
    image: "/images/aloo-tikki-burger.jpg",
  },
  {
    id: "17",
    name: "Aloo Tikki Cheese Burger",
    description: "Classic potato patty burger with melted cheese slice",
    price: 80,
    category: "burger",
    image: "/images/cheese-aloo-burger.jpg",
  },
  {
    id: "18",
    name: "Spicy Tandoori Burger",
    description: "Tandoori-marinated patty with mint mayo and veggies",
    price: 120,
    category: "burger",
    image: "/images/tandoori-burger.jpg",
  },
  {
    id: "19",
    name: "Paneer Patty Burger",
    description: "Grilled cottage cheese patty with spicy sauces",
    price: 140,
    category: "burger",
    image: "/images/paneer-burger.jpg",
  },
  {
    id: "20",
    name: "Paneer Cheese Patty Burger",
    description: "Paneer patty with double cheese and garlic mayo",
    price: 160,
    category: "burger",
    image: "/images/paneer-cheese-burger.jpg",
  },
];

export default menuItems;
